'use client';

import { ChangeEvent, DragEvent, useRef, useState } from 'react';

type Specs = { size: string; colour: string; copies: number; sides: string; finish: string };
const initialSpecs: Specs = { size: 'A4', colour: 'Colour', copies: 1, sides: 'Single-sided', finish: 'No binding' };

export default function PrintPortal() {
  const [phase, setPhase] = useState<'splash' | 'upload' | 'specs' | 'payment' | 'done'>('splash');
  const [file, setFile] = useState<File | null>(null);
  const [specs, setSpecs] = useState<Specs>(initialSpecs);
  const input = useRef<HTMLInputElement>(null);
  const accept = (f?: File) => { if (f) { setFile(f); setPhase('specs'); } };
  const onDrop = (e: DragEvent<HTMLButtonElement>) => { e.preventDefault(); accept(e.dataTransfer.files[0]); };
  const price = (specs.copies * (specs.colour === 'Colour' ? 1.2 : .45) + (specs.finish === 'No binding' ? 0 : 1.5)).toFixed(2);
  return <main className="site-shell">
    <header className="topbar"><a className="brand" href="/"><span className="brand-mark">Q</span> QRPrint</a><div className="store-pill"><i /> PrintSpot · Riverwalk</div><button className="help">Help centre ↗</button></header>
    {phase === 'splash' && <section className="splash"><div className="float-orbit orbit-one"/><div className="float-orbit orbit-two"/><p className="eyebrow">WELCOME TO PRINTSPOT</p><h1>Your files.<br/><em>Ready when you are.</em></h1><p className="lede">Upload, customise and collect — all in a few simple steps.</p><button className="primary big" onClick={() => setPhase('upload')}>Start a print order <span>→</span></button><div className="mini-proof"><b>01</b><span>Upload files</span><b>02</b><span>Set preferences</span><b>03</b><span>Collect with a code</span></div></section>}
    {phase !== 'splash' && phase !== 'done' && <><div className="progress"><span className={phase === 'upload' ? 'active' : 'complete'}>1 <small>Upload</small></span><hr/><span className={phase === 'specs' ? 'active' : phase === 'payment' ? 'complete' : ''}>2 <small>Preferences</small></span><hr/><span className={phase === 'payment' ? 'active' : ''}>3 <small>Payment</small></span></div>
    {phase === 'upload' && <section className="flow-card upload-view"><p className="eyebrow">STEP 01</p><h2>What are we printing?</h2><p className="subtle">PDFs work best. We also accept DOCX, PPTX, PNG and JPG files up to 50 MB.</p><button className="dropzone" onClick={() => input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={onDrop}><span className="upload-icon">↑</span><b>Drop your document here</b><small>or browse files from your device</small></button><input className="hidden" ref={input} type="file" accept=".pdf,.docx,.pptx,.png,.jpg,.jpeg" onChange={(e: ChangeEvent<HTMLInputElement>)=>accept(e.target.files?.[0])}/><p className="secure">⌁ Your files are encrypted and automatically deleted after collection.</p></section>}
    {phase === 'specs' && <section className="flow-card specs-view"><div className="file-row"><div className="file-icon">PDF</div><div><b>{file?.name || 'Quarterly-report.pdf'}</b><p>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB` : '2.4 MB'} · Ready to print</p></div><button onClick={()=>setPhase('upload')}>Replace</button></div><p className="eyebrow">STEP 02</p><h2>Make it yours.</h2><div className="options"><Option label="Paper size" value={specs.size} values={['A4','A3','A5']} onChange={v=>setSpecs({...specs,size:v})}/><Option label="Print in" value={specs.colour} values={['Colour','Black & white']} onChange={v=>setSpecs({...specs,colour:v})}/><Option label="Sides" value={specs.sides} values={['Single-sided','Double-sided']} onChange={v=>setSpecs({...specs,sides:v})}/><Option label="Finish" value={specs.finish} values={['No binding','Stapled','Spiral bound']} onChange={v=>setSpecs({...specs,finish:v})}/></div><div className="copies"><span>Copies</span><div><button onClick={()=>setSpecs({...specs,copies:Math.max(1,specs.copies-1)})}>−</button><b>{specs.copies}</b><button onClick={()=>setSpecs({...specs,copies:specs.copies+1})}>+</button></div></div><button className="primary full" onClick={()=>setPhase('payment')}>Review & pay <span>→</span></button></section>}
    {phase === 'payment' && <section className="flow-card payment-view"><p className="eyebrow">STEP 03</p><h2>Almost there.</h2><div className="receipt"><div><span>{file?.name || 'Your document'}</span><b>£{price}</b></div><div><span>{specs.size} · {specs.colour} · {specs.copies} copy{specs.copies > 1 ? 'ies' : ''}</span><span>{specs.finish}</span></div><hr/><div className="total"><b>Total</b><strong>£{price}</strong></div></div><label className="payment-choice"><input type="radio" defaultChecked name="pay"/><span className="card-logo">▣</span><b>Card payment</b><small>Visa, Mastercard, Amex</small></label><label className="payment-choice"><input type="radio" name="pay"/><span className="paypal">P</span><b>PayPal</b><small>Pay securely with PayPal</small></label><button className="primary full" onClick={()=>setPhase('done')}>Pay £{price} <span>→</span></button><p className="secure">🔒 Payments are processed securely by Stripe.</p></section>}</>}
    {phase === 'done' && <section className="success"><div className="check">✓</div><p className="eyebrow">ORDER CONFIRMED</p><h1>It&apos;s on its way<br/>to the printer.</h1><p className="lede">Show this collection code at the counter when your order is ready.</p><div className="code"><small>YOUR COLLECTION CODE</small><strong>R7K4M9</strong></div><div className="ready"><span>●</span><div><b>Usually ready in 10–15 minutes</b><p>We&apos;ll keep your order for 24 hours.</p></div></div><button className="secondary" onClick={()=>{setFile(null);setSpecs(initialSpecs);setPhase('splash')}}>Start another order</button></section>}
    <footer><span>© 2025 QRPrint</span><span>Powered by local people & good printers.</span><span>Privacy · Terms</span></footer>
  </main>;
}

function Option({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (v:string)=>void }) { return <label className="option"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>; }
