'use client';
import { useState } from 'react';
export default function CustomerPrintPage() {
  const [file, setFile] = useState(null); const [form, setForm] = useState({ paperSize: 'A4', colourMode: 'bw', sides: 'single', copies: 1, paperType: 'normal', binding: 'none', instructions: '' });
  const [quote, setQuote] = useState(null); const [error, setError] = useState(''); const shop = new URLSearchParams(typeof window === 'undefined' ? '' : window.location.search).get('shop');
  const canQuote = Boolean(shop && file);
  const update = (name, value) => setForm((current) => ({ ...current, [name]: value }));
  async function getQuote(event) { event.preventDefault(); setError(''); setQuote(null); if (!canQuote) { setError('Scan the QR code displayed by your shop, then choose your document.'); return; }
    const response = await fetch('/api/quotes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ merchantSlug: shop, documentId: file.name, specifications: form }) });
    const body = await response.json(); if (!response.ok) { setError(body.error || 'A live quote is unavailable. Ask the counter for help.'); return; } setQuote(body); }
  return <main><h1>Send a print job</h1><p>{shop ? 'Choose your document and print preferences.' : 'Scan the shop QR code to open its unique order page.'}</p><form onSubmit={getQuote}><label>Document <input required type="file" accept=".pdf,.doc,.docx,image/*" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><label>Paper size <select value={form.paperSize} onChange={(e) => update('paperSize', e.target.value)}><option>A4</option><option>A3</option><option>legal</option><option>letter</option></select></label><label>Colour <select value={form.colourMode} onChange={(e) => update('colourMode', e.target.value)}><option value="bw">Black & white</option><option value="colour">Colour</option></select></label><label>Sides <select value={form.sides} onChange={(e) => update('sides', e.target.value)}><option value="single">Single-sided</option><option value="double">Double-sided</option></select></label><label>Copies <input min="1" max="1000" type="number" value={form.copies} onChange={(e) => update('copies', Number(e.target.value))} /></label><label>Paper <select value={form.paperType} onChange={(e) => update('paperType', e.target.value)}><option value="normal">Normal</option><option value="glossy">Glossy</option><option value="matte">Matte</option></select></label><label>Binding <select value={form.binding} onChange={(e) => update('binding', e.target.value)}><option value="none">None</option><option value="spiral">Spiral</option><option value="thermal">Thermal</option></select></label><label>Instructions <textarea maxLength="500" value={form.instructions} onChange={(e) => update('instructions', e.target.value)} /></label><button disabled={!canQuote}>Get live quote</button></form>{error && <p role="alert">{error}</p>}{quote && <section><h2>{quote.currency} {quote.amount}</h2><p>Quote expires at {new Date(quote.expiresAt).toLocaleString()}.</p><p>Continue to the payment option provided by your shop.</p></section>}</main>;
}
